/* MWS Ecosystem module + tech stack data */

export const ECOSYSTEM_MODULES = [
  { id: 'emotion', title: 'Emotional Intelligence', icon: '🧠', color: '#a78bfa', desc: 'AI-powered emotion check-in, face detection, pattern analysis, and wellness tracking for students and staff.', tech: ['Gemini Flash', 'TensorFlow.js', 'MediaPipe', 'Face Mesh'], pages: ['Emotional Check-in', 'Staff Check-in', 'Face Scan Verification', 'Emotion History', 'Emotion Patterns'], routes: ['/emotional-checkin', '/emotional-checkin/staff', '/emotional-checkin/face-scan'], stats: { pages: 5, apis: 8, models: 1 } },
  { id: 'ai-chat', title: 'AI Student Assistant', icon: '💬', color: '#38bdf8', desc: 'Conversational AI chat for students with context-aware responses, operation execution, and learning support.', tech: ['Arcee AI Trinity', 'OpenRouter', 'Socket.IO', 'Prompt Engine'], pages: ['Student AI Chat', 'AI Check-in Chat', 'Assistant Profile'], routes: ['/student/ai-chat', '/student/emotional-checkin/ai', '/ai-assistant'], stats: { pages: 3, apis: 6, models: 1 } },
  { id: 'staff-chat', title: 'Staff AI Assistant', icon: '🤖', color: '#34d399', desc: 'AI-powered chat assistant for staff and employees, enabling operational support, report generation, and workflow assistance.', tech: ['StepFun Step 3.5 Flash', 'OpenRouter', 'Prompt Engine'], pages: ['Staff AI Chat', 'Head Unit Briefing'], routes: ['/ai-assistant'], stats: { pages: 2, apis: 4, models: 1 } },
  { id: 'insights', title: 'Teacher AI Insights', icon: '📊', color: '#f472b6', desc: 'AI-generated student insights, alert system, severity detection, and batch alert generation for teachers.', tech: ['Gemini Flash', 'MongoDB Aggregation', 'Pattern Detection'], pages: ['Teacher Dashboard', 'Alert Management', 'Student Analytics'], routes: ['/emotional-checkin/teacher-dashboard'], stats: { pages: 3, apis: 10, models: 1 } },
  { id: 'mtss', title: 'MTSS Support System', icon: '🛡️', color: '#fbbf24', desc: 'Multi-Tiered System of Support — student portal, mentor assignment, tier tracking, and intervention strategies.', tech: ['Real-time Socket', 'Role-based Access', 'MongoDB'], pages: ['Student Portal', 'Student Profile', 'Teacher Dashboard', 'Admin Dashboard', 'Mentor Assignment'], routes: ['/mtss/student-portal', '/mtss/teacher', '/mtss/admin'], stats: { pages: 5, apis: 12, models: 0 } },
  { id: 'auth', title: 'Auth & User Management', icon: '🔐', color: '#fb923c', desc: 'Google OAuth, JWT tokens, role-based access control (RBAC), organization management, and user lifecycle.', tech: ['Google OAuth', 'JWT', 'Bcrypt', 'Express RBAC'], pages: ['Login/OAuth', 'Role Selection', 'Profile', 'User Management'], routes: ['/auth/callback', '/select-role', '/profile', '/user-management'], stats: { pages: 4, apis: 6, models: 0 } },
  { id: 'dashboard', title: 'Executive Dashboards', icon: '📈', color: '#22d3ee', desc: 'Head unit briefing, KPI monitoring, emotion trend overview, and export-ready reporting dashboards.', tech: ['Recharts', 'Real-time Socket', 'Aggregation Pipelines'], pages: ['Head Unit Dashboard', 'Individual Wellness', 'Personal Stats'], routes: ['/emotional-checkin/dashboard', '/emotional-wellness', '/profile/personal-stats'], stats: { pages: 3, apis: 5, models: 0 } },
  { id: 'notifications', title: 'Notification Engine', icon: '🔔', color: '#c084fc', desc: 'Real-time push notifications, email delivery via Nodemailer, Slack integration, and per-user preferences.', tech: ['Socket.IO', 'Nodemailer', 'Slack API', 'Push Events'], pages: ['Notification Center', 'Notification Settings'], routes: ['/notifications', '/notifications/settings'], stats: { pages: 2, apis: 8, models: 0 } },
  { id: 'devtools', title: 'Developer Tools', icon: '🔧', color: '#94a3b8', desc: 'AI network topology, real-time telemetry, flow visualization, and presentation-mode monitoring.', tech: ['SVG Canvas', 'WebSocket Telemetry', 'In-memory Engine'], pages: ['AI Topology', 'MWS Ecosystem', 'Executive Presentation'], routes: ['/dev/ai-topology'], stats: { pages: 2, apis: 2, models: 0 } },
];

export const ECOSYSTEM_TECH_STACK = [
  { category: 'Frontend', items: ['React 18', 'Redux Toolkit', 'Tailwind CSS', 'Framer Motion', 'GSAP', 'Anime.js', 'Recharts', 'Lucide Icons', 'Radix UI'] },
  { category: 'Backend', items: ['Express 5', 'Mongoose ODM', 'Socket.IO', 'JWT Auth', 'Rate Limiter', 'Winston Logger', 'Joi Validation'] },
  { category: 'AI / ML', items: ['Google Gemini Flash', 'Arcee AI Trinity', 'StepFun Step 3.5', 'TensorFlow.js', 'MediaPipe Face Mesh', 'OpenRouter API'] },
  { category: 'Data', items: ['MongoDB Atlas', 'Redis Cache', 'S3 Audit Storage', 'Vector Embeddings'] },
  { category: 'DevOps', items: ['Docker Compose', 'Vite Build', 'PWA Service Worker', 'Helmet Security'] },
  { category: 'Integrations', items: ['Google OAuth', 'Slack Bot', 'Nodemailer', 'WebSocket Real-time'] },
];
