/* Node + edge definitions for the AI topology graph */

export const NODE_META = {
  'hub-core': { label: 'MWS Hub Core', short: 'HUB', ring: 0, layer: 'hub', purpose: 'Central orchestration hub — routes every AI & data request across the platform.', methods: ['routeRequest', 'broadcastEvent', 'healthCheck'], apis: ['/api/v1/*'], icon: '⬡' },
  'ai-google-gemini': { label: 'Google Gemini Flash', short: 'GEMINI', ring: 1, layer: 'ai', purpose: 'Primary AI model for emotion analysis, student AI check-in, and teacher insight generation via Gemini Flash.', methods: ['generateContent', 'analyzeEmotion', 'generateInsights'], apis: ['Gemini Flash API', 'Gemini 1.5 Flash Vision'], icon: '◈' },
  'ai-openai-gpt': { label: 'Arcee AI: Trinity Large', short: 'TRINITY', ring: 1, layer: 'ai', purpose: 'Student AI chat — powered by Arcee AI: Trinity Large Preview (free) via OpenRouter.', methods: ['chatCompletion', 'streamResponse', 'contextAssembly'], apis: ['OpenRouter API → arcee-ai/trinity-large-preview:free'], icon: '◈' },
  'ai-anthropic-claude': { label: 'StepFun: Step 3.5 Flash', short: 'STEP 3.5', ring: 1, layer: 'ai', purpose: 'Staff/employee AI chat — powered by StepFun: Step 3.5 Flash (free) via OpenRouter.', methods: ['chatCompletion', 'staffAssist', 'fallbackGenerate'], apis: ['OpenRouter API → stepfun/step-3.5-flash:free'], icon: '◈' },
  'be-api-gateway': { label: 'API Gateway', short: 'GATEWAY', ring: 2, layer: 'backend', purpose: 'Express.js API gateway — routes /api/v1/* requests with rate limiting and CORS.', methods: ['routeMiddleware', 'rateLimiter', 'corsHandler'], apis: ['/api/v1/ai-chat/*', '/api/v1/ai-insights/*', '/api/v1/dev/topology/*'], icon: '▣' },
  'be-auth-rbac': { label: 'Auth & RBAC', short: 'AUTH', ring: 2, layer: 'backend', purpose: 'JWT authentication and role-based access control middleware.', methods: ['authenticate', 'authorize', 'validateToken'], apis: ['middleware/auth.authenticate', 'middleware/auth.authorize'], icon: '▣' },
  'be-ai-orchestrator': { label: 'AI Orchestrator', short: 'ORCH', ring: 2, layer: 'backend', purpose: 'Orchestrates AI provider calls with fallback chains and telemetry hooks.', methods: ['orchestrateChat', 'orchestrateInsight', 'selectProvider'], apis: ['aiChatService.chat', 'aiInsightService.*'], icon: '▣' },
  'be-prompt-engine': { label: 'Prompt Engine', short: 'PROMPT', ring: 2, layer: 'backend', purpose: 'Builds and assembles AI prompts with context, persona, and safety constraints.', methods: ['buildPrompt', 'assembleContext', 'applyPersona'], apis: ['ai/prompts/*', 'ai/utils/*'], icon: '▣' },
  'be-stream-broker': { label: 'Stream Broker', short: 'STREAM', ring: 2, layer: 'backend', purpose: 'Socket.IO real-time event broker for live dashboard and topology updates.', methods: ['broadcastRoom', 'joinRoom', 'leaveRoom'], apis: ['socket.io room: dev-topology', 'socket.io event: dev-topology:update'], icon: '▣' },
  'be-telemetry': { label: 'Telemetry Service', short: 'TELEMETRY', ring: 2, layer: 'backend', purpose: 'In-memory telemetry engine — tracks node/edge activity with debounced broadcast.', methods: ['recordFlow', 'recordProviderCall', 'getSnapshot'], apis: ['/api/v1/dev/topology/snapshot', '/api/v1/dev/topology/health'], icon: '▣' },
  'db-mongodb': { label: 'MongoDB Atlas', short: 'MONGO', ring: 3, layer: 'data', purpose: 'Primary data store — users, check-ins, conversations, alerts, MTSS data.', methods: ['find', 'aggregate', 'insertOne', 'updateOne'], apis: ['mongoose ODM'], icon: '⬢' },
  'db-redis-cache': { label: 'Redis Cache', short: 'REDIS', ring: 3, layer: 'data', purpose: 'In-memory cache layer for session data and rate-limit counters.', methods: ['get', 'set', 'expire', 'incr'], apis: ['node-cache (in-memory proxy)'], icon: '⬢' },
  'db-vector-store': { label: 'Vector Store', short: 'VECTOR', ring: 3, layer: 'data', purpose: 'Embedding storage for semantic search and context retrieval.', methods: ['upsert', 'query', 'similaritySearch'], apis: ['vector embeddings'], icon: '⬢' },
  'db-s3-audit': { label: 'S3 Audit Log', short: 'AUDIT', ring: 3, layer: 'data', purpose: 'Persistent audit trail for AI telemetry and compliance records.', methods: ['putObject', 'getObject'], apis: ['S3-compatible storage'], icon: '⬢' },
  'fe-dev-topology': { label: 'Dev Topology', short: 'TOPOLOGY', ring: 4, layer: 'frontend', purpose: 'This page — developer network topology dashboard for AI monitoring.', methods: ['fetchSnapshot', 'subscribeSocket', 'renderCanvas'], apis: ['/dev/ai-topology'], icon: '◻' },
  'fe-student-ai-chat': { label: 'Student AI Chat', short: 'AI CHAT', ring: 4, layer: 'frontend', purpose: 'Interactive AI chat page for student support (Arcee AI Trinity) with conversation history.', methods: ['sendMessage', 'loadHistory', 'streamResponse'], apis: ['/student/ai-chat'], icon: '◻' },
  'fe-student-ai-checkin': { label: 'Student AI Check-in', short: 'AI CHECKIN', ring: 4, layer: 'frontend', purpose: 'AI-powered emotional check-in with face detection and Gemini analysis.', methods: ['submitCheckin', 'analyzeFace', 'processEmotion'], apis: ['/student/emotional-checkin/ai'], icon: '◻' },
  'fe-teacher-insights': { label: 'Teacher Insights', short: 'INSIGHTS', ring: 4, layer: 'frontend', purpose: 'Teacher dashboard for AI-generated student insights and alerts.', methods: ['fetchInsights', 'generateAlerts', 'viewPatterns'], apis: ['/emotional-checkin/teacher-dashboard'], icon: '◻' },
  'fe-mtss-portal': { label: 'MTSS Portal', short: 'MTSS', ring: 4, layer: 'frontend', purpose: 'Multi-Tiered System of Support student portal with mentor tracking.', methods: ['viewTier', 'trackProgress', 'contactMentor'], apis: ['/mtss/student-portal'], icon: '◻' },
  'fe-head-unit-briefing': { label: 'Head Unit Briefing', short: 'BRIEFING', ring: 4, layer: 'frontend', purpose: 'Executive dashboard for head unit — emotion check-in overview and KPI monitoring.', methods: ['fetchBriefing', 'viewTrends', 'exportReport'], apis: ['/emotional-checkin/dashboard'], icon: '◻' },
  'fe-admin-user-management': { label: 'Admin User Mgmt', short: 'USERS', ring: 4, layer: 'frontend', purpose: 'Admin panel for managing user accounts, roles, and organization settings.', methods: ['listUsers', 'updateRole', 'importBatch'], apis: ['/user-management'], icon: '◻' },
  'fe-executive-presentation': { label: 'Executive Presentation', short: 'PRESENT', ring: 4, layer: 'frontend', purpose: 'Presentation-mode topology view for executive stakeholder demonstrations.', methods: ['enterPresentMode', 'autoPlay', 'exportSlide'], apis: ['/dev/ai-topology?mode=present'], icon: '◻' },
};

export const EDGE_DEF = {
  'e-hub-gpt': { from: 'hub-core', to: 'ai-openai-gpt' },
  'e-hub-claude': { from: 'hub-core', to: 'ai-anthropic-claude' },
  'e-hub-gemini': { from: 'hub-core', to: 'ai-google-gemini' },
  'e-hub-api': { from: 'hub-core', to: 'be-api-gateway' },
  'e-hub-orch': { from: 'hub-core', to: 'be-ai-orchestrator' },
  'e-hub-stream': { from: 'hub-core', to: 'be-stream-broker' },
  'e-gpt-orch': { from: 'ai-openai-gpt', to: 'be-ai-orchestrator' },
  'e-claude-orch': { from: 'ai-anthropic-claude', to: 'be-ai-orchestrator' },
  'e-gemini-orch': { from: 'ai-google-gemini', to: 'be-ai-orchestrator' },
  'e-gpt-prompt': { from: 'ai-openai-gpt', to: 'be-prompt-engine' },
  'e-claude-prompt': { from: 'ai-anthropic-claude', to: 'be-prompt-engine' },
  'e-api-auth': { from: 'be-api-gateway', to: 'be-auth-rbac' },
  'e-api-orch': { from: 'be-api-gateway', to: 'be-ai-orchestrator' },
  'e-auth-orch': { from: 'be-auth-rbac', to: 'be-ai-orchestrator' },
  'e-orch-prompt': { from: 'be-ai-orchestrator', to: 'be-prompt-engine' },
  'e-orch-telemetry': { from: 'be-ai-orchestrator', to: 'be-telemetry' },
  'e-orch-mongo': { from: 'be-ai-orchestrator', to: 'db-mongodb' },
  'e-prompt-vector': { from: 'be-prompt-engine', to: 'db-vector-store' },
  'e-stream-redis': { from: 'be-stream-broker', to: 'db-redis-cache' },
  'e-telemetry-s3': { from: 'be-telemetry', to: 'db-s3-audit' },
  'e-fe-dev-api': { from: 'fe-dev-topology', to: 'be-api-gateway' },
  'e-fe-chat-api': { from: 'fe-student-ai-chat', to: 'be-api-gateway' },
  'e-fe-checkin-api': { from: 'fe-student-ai-checkin', to: 'be-api-gateway' },
  'e-fe-teacher-api': { from: 'fe-teacher-insights', to: 'be-api-gateway' },
  'e-fe-mtss-api': { from: 'fe-mtss-portal', to: 'be-api-gateway' },
  'e-fe-head-api': { from: 'fe-head-unit-briefing', to: 'be-api-gateway' },
  'e-fe-admin-api': { from: 'fe-admin-user-management', to: 'be-api-gateway' },
  'e-fe-pres-api': { from: 'fe-executive-presentation', to: 'be-api-gateway' },
};

export const RING_RADII = [0, 112, 212, 298, 388];
