/* Simulator flow definitions — fallback when backend is offline */

export const SIM_FLOWS = [
  { key: 'ai_chat_message', label: 'Student AI Chat (Trinity)', model: 'ai-openai-gpt', nodes: ['fe-student-ai-chat', 'be-api-gateway', 'be-auth-rbac', 'be-ai-orchestrator', 'be-prompt-engine', 'be-stream-broker', 'db-mongodb', 'be-telemetry', 'hub-core', 'ai-openai-gpt'], edges: ['e-fe-chat-api', 'e-api-auth', 'e-auth-orch', 'e-api-orch', 'e-orch-prompt', 'e-hub-api', 'e-hub-orch', 'e-hub-stream', 'e-orch-mongo', 'e-orch-telemetry', 'e-hub-gpt', 'e-gpt-orch'] },
  { key: 'ai_checkin_submit', label: 'Student AI Check-in (Gemini)', model: 'ai-google-gemini', nodes: ['fe-student-ai-checkin', 'be-api-gateway', 'be-auth-rbac', 'be-ai-orchestrator', 'be-telemetry', 'db-mongodb', 'hub-core', 'ai-google-gemini'], edges: ['e-fe-checkin-api', 'e-api-auth', 'e-auth-orch', 'e-api-orch', 'e-gemini-orch', 'e-orch-mongo', 'e-orch-telemetry', 'e-hub-gemini'] },
  { key: 'ai_insights_student_insights', label: 'Teacher Insights (Gemini)', model: 'ai-google-gemini', nodes: ['fe-teacher-insights', 'be-api-gateway', 'be-auth-rbac', 'be-ai-orchestrator', 'be-telemetry', 'db-mongodb', 'hub-core', 'ai-google-gemini'], edges: ['e-fe-teacher-api', 'e-api-auth', 'e-auth-orch', 'e-api-orch', 'e-orch-telemetry', 'e-orch-mongo', 'e-gemini-orch', 'e-hub-gemini'] },
  { key: 'ai_insights_generate_alerts', label: 'Generate Alerts (Gemini)', model: 'ai-google-gemini', nodes: ['fe-teacher-insights', 'be-api-gateway', 'be-auth-rbac', 'be-ai-orchestrator', 'be-telemetry', 'db-s3-audit', 'db-mongodb', 'hub-core', 'ai-google-gemini'], edges: ['e-fe-teacher-api', 'e-api-auth', 'e-auth-orch', 'e-api-orch', 'e-gemini-orch', 'e-orch-telemetry', 'e-telemetry-s3', 'e-orch-mongo', 'e-hub-gemini'] },
  { key: 'staff_chat_message', label: 'Staff AI Chat (Step 3.5)', model: 'ai-anthropic-claude', nodes: ['fe-head-unit-briefing', 'be-api-gateway', 'be-auth-rbac', 'be-ai-orchestrator', 'be-prompt-engine', 'db-mongodb', 'be-telemetry', 'hub-core', 'ai-anthropic-claude'], edges: ['e-fe-head-api', 'e-api-auth', 'e-auth-orch', 'e-api-orch', 'e-orch-prompt', 'e-hub-orch', 'e-orch-mongo', 'e-orch-telemetry', 'e-hub-claude', 'e-claude-orch'] },
  { key: 'dev_topology_snapshot', label: 'Topology Snapshot', model: null, nodes: ['fe-dev-topology', 'be-api-gateway', 'be-telemetry', 'hub-core', 'db-mongodb'], edges: ['e-fe-dev-api', 'e-hub-api', 'e-hub-orch', 'e-orch-mongo'] },
  { key: 'ai_chat_assistant_profile', label: 'Assistant Profile', model: null, nodes: ['fe-student-ai-chat', 'be-api-gateway', 'be-auth-rbac', 'be-ai-orchestrator', 'db-mongodb', 'hub-core'], edges: ['e-fe-chat-api', 'e-api-auth', 'e-auth-orch', 'e-api-orch', 'e-orch-mongo', 'e-hub-api', 'e-hub-orch'] },
  { key: 'ai_chat_execute_operation', label: 'AI Operation (Trinity)', model: 'ai-openai-gpt', nodes: ['fe-student-ai-chat', 'be-api-gateway', 'be-auth-rbac', 'be-ai-orchestrator', 'be-telemetry', 'db-mongodb', 'hub-core', 'ai-openai-gpt'], edges: ['e-fe-chat-api', 'e-api-auth', 'e-auth-orch', 'e-api-orch', 'e-orch-mongo', 'e-orch-telemetry', 'e-hub-orch', 'e-hub-gpt', 'e-gpt-orch'] },
  { key: 'dev_topology_socket_subscribe', label: 'Socket Subscribe', model: null, nodes: ['fe-dev-topology', 'be-stream-broker', 'hub-core', 'be-telemetry'], edges: ['e-hub-stream', 'e-hub-orch', 'e-fe-dev-api'] },
  { key: 'fe_mtss_portal_load', label: 'MTSS Portal', model: null, nodes: ['fe-mtss-portal', 'be-api-gateway', 'be-auth-rbac', 'db-mongodb', 'hub-core'], edges: ['e-fe-mtss-api', 'e-api-auth', 'e-hub-api', 'e-orch-mongo'] },
  { key: 'fe_head_unit_load', label: 'Head Unit Briefing', model: null, nodes: ['fe-head-unit-briefing', 'be-api-gateway', 'be-auth-rbac', 'db-mongodb', 'hub-core'], edges: ['e-fe-head-api', 'e-api-auth', 'e-hub-api', 'e-orch-mongo'] },
  { key: 'fe_admin_user_mgmt', label: 'User Management', model: null, nodes: ['fe-admin-user-management', 'be-api-gateway', 'be-auth-rbac', 'db-mongodb', 'hub-core'], edges: ['e-fe-admin-api', 'e-api-auth', 'e-hub-api', 'e-orch-mongo'] },
  { key: 'fe_exec_presentation', label: 'Presentation View', model: null, nodes: ['fe-executive-presentation', 'be-api-gateway', 'be-telemetry', 'hub-core'], edges: ['e-fe-pres-api', 'e-hub-api', 'e-hub-orch'] },
];
